description: >
  Queue a Backup Environment Job

parameters:
  tool_path:
    type: env_var_name
    default: "DBMAESTRO_TOOL_PATH"
    description: "Path where the DBmaestroAgent.jar is located"
  project_name:
    type: string
    description: "DBmaestro project name"
  environment_name:
    type: string
    description: "DBmaestro environment name"
  backup_name:
    type: string
    description: "Backup name."
  backup_description:
    type: string
    default: ""
    description: "Backup description."
  ignore_env_version_mismatch:
    type: enum
    default: "True"
    description: "Ignore environment version mismatch"
    enum: ["True", "False"]
  server_address:
    type: env_var_name
    default: "DBMAESTRO_SERVER_ADDRESS"
    description: "DBmaestro server address"
  use_ssl:
    type: env_var_name
    description: "Use or don't use SSL/https protocol to connect to the DBmaestro agent. Default is n."
    default: "DBMAESTRO_USE_SSL"
  auth_type:
    type: env_var_name
    default: "DBMAESTRO_AUTH_TYPE"
    description: "DBmaestro auth type"
  username:
    type: env_var_name
    default: "DBMAESTRO_USERNAME"
    description: "DBmaestro username"
  password:
    type: env_var_name
    default: "DBMAESTRO_PASSWORD"
    description: "DBmaestro password"
steps:
  - run:
      environment:
        PDBM_TOOL_PATH: << parameters.tool_path >>
        DBM_PROJECT_NAME: << parameters.project_name >>
        DBM_ENVIRONMENT_NAME: << parameters.environment_name >>
        DBM_BACKUP_NAME: << parameters.backup_name >>
        DBM_BACKUP_DESCRIPTION: << parameters.backup_description >>
        DBM_IGNORE_ENV_VERSION_MISMATCH: << parameters.ignore_env_version_mismatch >>
        PDBM_SERVER_ADDRESS: << parameters.server_address >>
        PDBM_USE_SSL: << parameters.use_ssl >>
        PDBM_AUTH_TYPE: << parameters.auth_type >>
        PDBM_USERNAME: << parameters.username >>
        DBM_PASSWORD: << parameters.password >>
      name: Backup environment
      command: <<include(scripts/backup-environment.sh)>>
