description: >
  Queue a Build Environment job to the DBmaestro DevOps Platform

  Available in SQL Server projects only

parameters:
  tool_path:
    type: string
    default: ""
    description: "Path where the DBmaestroAgent.jar is located"
  project_name:
    type: string
    description: "DBmaestro project name"
  environment_name:
    type: string
    description: "DBmaestro environment name"
  version_type:
    type: enum
    description: "Specifies the version type to be used in build process"
    default: ""
    enum: ["latest", "label", "latestlabel", "changesets", "live", ""]
  label_name:
    type: string
    default: ""
    description: "Label name to be used or applied"
  baseline_label_name:
    type: string
    default: ""
    description: "Name of label to be used as baseline"
  package_name:
    type: string
    default: ""
    description: Package name
  version_level:
    type: enum
    default: ""
    description: "MAJOR or MINOR"
    enum: ["MAJOR", "MINOR", ""]
  after_current_deployed_version:
    type: enum
    default: "False"
    description: "Ignore environment version mismatch"
    enum: ["True", "False"]
  server_address:
    type: string
    default: ""
    description: "DBmaestro server address"
  use_ssl:
    type: enum
    description: "Use or don't use SSL/https protocol to connect to the DBmaestro agent. Default is n."
    default: ""
    enum: ["y", "n", ""]
  auth_type:
    type: enum
    default: ""
    description: "DBmaestro auth type"
    enum: ["DBmaestroAccount", "DomainLogin", ""]
  username:
    type: string
    default: ""
    description: "DBmaestro username"
  password:
    type: env_var_name
    default: "DBMAESTRO_PASSWORD"
    description: "DBmaestro password"
steps:
  - run:
      environment:
        DBM_TOOL_PATH: << parameters.tool_path >>
        DBM_PROJECT_NAME: << parameters.project_name >>
        DBM_ENVIRONMENT_NAME: << parameters.environment_name >>
        DBM_VERSION_TYPE: << parameters.version_type >>
        DBM_LABEL_NAME: << parameters.label_name >>
        DBM_BASELINE_LABEL_NAME: << parameters.baseline_label_name >>
        DBM_PACKAGE_NAME: << parameters.package_name >>
        DBM_VERSION_LEVEL: << parameters.version_level >>
        DBM_AFTER_CURRENT_DEPLOYED_VERSION: << parameters.after_current_deployed_version >>
        DBM_SERVER_ADDRESS: << parameters.server_address >>
        DBM_USE_SSL: << parameters.use_ssl >>
        DBM_AUTH_TYPE: << parameters.auth_type >>
        DBM_USERNAME: << parameters.username >>
        DBM_PASSWORD: << parameters.password >>
      name: Build
      command: <<include(scripts/build.sh)>>
