description: >
  Queue a Package Job to the DBmaestro DevOps Platform

  - Creates a Package for an Environment
  - If Oracle scripts do not include the buffer flush directive ('/') and CancelJob has been issued, then a warning will be displayed next to the script unless suppressed and ignored through the -IgnoreScriptWarnings parameter. This warning CAN also be ignored deliberately through the DBmaestro DevOps Platform interface.

parameters:
  tool_path:
    type: env_var_name
    default: "DBMAESTRO_TOOL_PATH"
    description: "Path where the DBmaestroAgent.jar is located"
  project_name:
    type: string
    description: "DBmaestro project name."
  file_path:
    type: string
    description: "Full .json file path to project."
  ignore_script_warnings:
    type: enum
    description: "Ignore/don't ignore warnings in scripts"
    default: "True"
    enum: ["True", "False"]
  server_address:
    type: env_var_name
    default: "DBMAESTRO_SERVER_ADDRESS"
    description: "DBmaestro server address"
  use_ssl:
    type: env_var_name
    description: "Use or don't use SSL/https protocol to connect to the DBmaestro agent. Default is n."
    default: "DBMAESTRO_USE_SSL"
  auth_type:
    type: env_var_name
    default: "DBMAESTRO_AUTH_TYPE"
    description: "DBmaestro auth type"
  username:
    type: env_var_name
    default: "DBMAESTRO_USERNAME"
    description: "DBmaestro username"
  password:
    type: env_var_name
    default: "DBMAESTRO_PASSWORD"
    description: "DBmaestro password"
steps:
  - run:
      environment:
        PDBM_TOOL_PATH: << parameters.tool_path >>
        DBM_PROJECT_NAME: << parameters.project_name >>
        DBM_FILE_PATH: << parameters.file_path >>
        DBM_IGNORE_SCRIPT_WARNINGS: << parameters.ignore_script_warnings >>
        PDBM_SERVER_ADDRESS: << parameters.server_address >>
        PDBM_USE_SSL: << parameters.use_ssl >>
        PDBM_AUTH_TYPE: << parameters.auth_type >>
        PDBM_USERNAME: << parameters.username >>
        DBM_PASSWORD: << parameters.password >>
      name: Package
      command: <<include(scripts/package.sh)>>
