description: >
  Queue a Package Job to the DBmaestro DevOps Platform

  - Creates a Package for an Environment
  - If Oracle scripts do not include the buffer flush directive ('/') and CancelJob has been issued, then a warning will be displayed next to the script unless suppressed and ignored through the -IgnoreScriptWarnings parameter. This warning CAN also be ignored deliberately through the DBmaestro DevOps Platform interface.

parameters:
  tool_path:
    type: string
    default: ""
    description: "Path where the DBmaestroAgent.jar is located"
  project_name:
    type: string
    description: "DBmaestro project name."
  file_path:
    type: string
    description: "Full .json file path to project."
  ignore_script_warnings:
    type: enum
    description: "Ignore/don't ignore warnings in scripts"
    default: "True"
    enum: ["True", "False"]
  server_address:
    type: string
    default: ""
    description: "DBmaestro server address"
  use_ssl:
    type: enum
    description: "Use or don't use SSL/https protocol to connect to the DBmaestro agent. Default is n."
    default: ""
    enum: ["y", "n", ""]
  auth_type:
    type: enum
    default: ""
    description: "DBmaestro auth type"
    enum: ["DBmaestroAccount", "DomainLogin", ""]
  username:
    type: string
    default: ""
    description: "DBmaestro username"
steps:
  - run:
      environment:
        DBM_TOOL_PATH: << parameters.tool_path >>
        DBM_PROJECT_NAME: << parameters.project_name >>
        DBM_FILE_PATH: << parameters.file_path >>
        DBM_IGNORE_SCRIPT_WARNINGS: << parameters.ignore_script_warnings >>
        DBM_SERVER_ADDRESS: << parameters.server_address >>
        DBM_USE_SSL: << parameters.use_ssl >>
        DBM_AUTH_TYPE: << parameters.auth_type >>
        DBM_USERNAME: << parameters.username >>
      name: Package
      command: <<include(scripts/package.sh)>>
