description: >
  Restore an Environment from a saved Backup

parameters:
  tool_path:
    type: string
    default: ""
    description: "Path where the DBmaestroAgent.jar is located"
  project_name:
    type: string
    description: "DBmaestro project name"
  environment_name:
    type: string
    description: "DBmaestro environment name"
  backup_name:
    type: string
    description: "Backup name."
  force_set_version:
    type: enum
    default: "False"
    description: "Ignore environment version mismatch"
    enum: ["True", "False"]
  server_address:
    type: string
    default: ""
    description: "DBmaestro server address"
  use_ssl:
    type: enum
    description: "Use or don't use SSL/https protocol to connect to the DBmaestro agent. Default is n."
    default: ""
    enum: ["y", "n", ""]
  auth_type:
    type: enum
    default: ""
    description: "DBmaestro auth type"
    enum: ["DBmaestroAccount", "DomainLogin", ""]
  username:
    type: string
    default: ""
    description: "DBmaestro username"
  password:
    type: env_var_name
    default: "DBMAESTRO_PASSWORD"
    description: "DBmaestro password"
steps:
  - run:
      environment:
        DBM_TOOL_PATH: << parameters.tool_path >>
        DBM_PROJECT_NAME: << parameters.project_name >>
        DBM_ENVIRONMENT_NAME: << parameters.environment_name >>
        DBM_BACKUP_NAME: << parameters.backup_name >>
        DBM_FORCE_SET_VERSION: << parameters.force_set_version >>
        DBM_SERVER_ADDRESS: << parameters.server_address >>
        DBM_USE_SSL: << parameters.use_ssl >>
        DBM_AUTH_TYPE: << parameters.auth_type >>
        DBM_USERNAME: << parameters.username >>
        DBM_PASSWORD: << parameters.password >>
      name: Restore environment
      command: |
        if [ -z "${DBM_TOOL_PATH:=${DBMAESTRO_TOOL_PATH:-'tools/dbmaestro'}}" ]; then echo "DBmaestro tool path is not set"&&exit 1; fi
        if [ -z "${DBM_SERVER_ADDRESS:=$DBMAESTRO_SERVER_ADDRESS}" ]; then echo "DBmaestro server address is not set"&&exit 1; fi
        if [ -z "${DBM_USE_SSL:=${DBMAESTRO_USE_SSL:-n}}" ]; then echo "DBmaestro SSL usage is not set"&&exit 1; fi
        if [ -z "${DBM_AUTH_TYPE:=${DBMAESTRO_AUTH_TYPE:-DBmaestroAccount}}" ]; then echo "DBmaestro auth type is not set"&&exit 1; fi
        if [ -z "${DBM_USERNAME:=$DBMAESTRO_USERNAME}" ]; then echo "DBmaestro username is not set"&&exit 1; fi
        if [ -z "${DBM_PWD:=${!DBM_PASSWORD}}" ]; then echo "DBMAESTRO_PASSWORD variable is not set"&&exit 1; fi
        java -jar "$DBM_TOOL_PATH/DBmaestroAgent.jar" -RestoreEnvironment -ProjectName "$DBM_PROJECT_NAME" -EnvName "$DBM_ENVIRONMENT_NAME" -BackupName "$DBM_BACKUP_NAME" -ForceSetVer "$DBM_FORCE_SET_VERSION" -Server "$DBM_SERVER_ADDRESS" -AuthType "$DBM_AUTH_TYPE" -UserName "$DBM_USERNAME" -Password "$DBM_PWD"

